#!/usr/bin/env bash
set -e

# TODO rotate the existing archive to a backup, so we're not potentially destroying important data

# Archive the entire CA, and also just the intermediate CA
tar -czvf /root/ca_persist/ca_authority.tar.gz -C /root/ca/ .
tar -czvf /root/ca_persist/intermediate_authority.tar.gz -C /root/ca/intermediate/ .
