site_name: Certificate Authority Guide
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - bash
site_description: A guide to managing a Certificate Authority, as would be used on a private LAN with private domains.
site_author: Jonathan Hanson
repo_url: https://github.com/triplepoint/certificate-authority-guide
edit_uri: blob/master/mkdocs/docs/
nav:
  - Introduction: index.md
  - Operational Overview and Setup: details_and_setup.md
  - Generating a Certificate Authority: generating_ca.md
  - Root Certificate Distribution: distribution.md
  - Service Certificates: service_certificates.md
  - Revoking Certificates: revocation_certificates.md
  - References: references.md
